title: PP, the marketeer
logo: /assets/img/ppa_profile.png
description: Data-Driven Marketer | Media Buying Expert | Analyzing the Numbers to Drive Results
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
